In [6]:
import numpy as np
import matplotlib.pyplot as plt
#imports numpy and matplot cause I think I'll need them for this

In [7]:
def sin(a=0.0):
    sinxresult=np.sin(a)
    return sinxresult
def cos(b=0.0):
    cosxresult=np.cos(b)
    return cosxresult
#defines two funcions, with them just being cosx and sinx

In [93]:

#turns x into an equally spaced array of 1000 numbers between 0 to 2pi, which I think is what tabulate means
x=np.linspace(0,2*np.pi, 1000)

#sets i into a range of 10 and has d equal the first i values of x (10 values of x)
for i in range(0,10):
    d=x[i]
    arr=np.array([d, sin(a=d),cos(b=d)])
    #creates an array using that d value which is the first 10 values of x, using that d value to plug into sin, cos, and just itself, finally printing it into its default of 3 collums.

    
    print(arr)





[0. 0. 1.]
[0.00628947 0.00628943 0.99998022]
[0.01257895 0.01257862 0.99992089]
[0.01886842 0.0188673  0.999822  ]
[0.0251579  0.02515525 0.99968356]
[0.03144737 0.03144219 0.99950557]
[0.03773685 0.03772789 0.99928805]
[0.04402632 0.0440121  0.999031  ]
[0.0503158  0.05029457 0.99873443]
[0.05660527 0.05657505 0.99839835]
